### ISSUE TITLE
--shamefully-hoist not needed

### ISSUE THREAD

**Issue by adev73** [beenotung/create-react-ts-template#1]
Not sure what version of pnpm fixed this, but you don't need to use "--shamefully-hoist" any more :) I'm using v6.14.6, so I suspect any v6.x would be the same.

**Comment by beenotung** [comment]
I agree the suggestion, will update it soon

**Comment by beenotung** [comment]
The package no longer suggest to run pnpm install with shamefully-hoist since v1.0.9 :)
